# Generated by Django 5.2 on 2025-05-08 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='given_by',
        ),
        migrations.AddField(
            model_name='flower',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drawingart',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_artworks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artworks/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art_type', models.CharField(choices=[('fine_arts', 'Fine Arts'), ('photography_cinematics', 'Photography & Cinematics'), ('abstract_art', 'Abstract Art'), ('conceptual_mixed_media', 'Conceptual & Mixed Media'), ('fashion_wearable_art', 'Fashion & Wearable Art')], default='design_illustration', max_length=50)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('flowers', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockchain', models.CharField(blank=True, choices=[('ethereum', 'Ethereum'), ('polygon', 'Polygon'), ('solana', 'Solana'), ('other', 'Other')], max_length=100, null=True)),
                ('mint_date', models.DateTimeField(blank=True, null=True)),
                ('nft_contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('nft_token_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_nft', models.BooleanField(default=False)),
                ('nft_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
