# Generated by Django 5.2 on 2025-06-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(max_length=255),
        ),
    ]
