# Generated by Django 5.2 on 2025-07-05 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='flowers',
            field=models.ManyToManyField(blank=True, db_table='profiles_artwork_flowers', related_name='flowered_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
