# Generated by Django 5.2.1 on 2025-05-22 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_artwork_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='flowers',
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowered_artworkgalleries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thriftstoreitem',
            name='image',
            field=models.ImageField(upload_to='thrift_images/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowered_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
