# Generated by Django 5.2.1 on 2025-05-08 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_flower_artist_remove_flower_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fashionart',
            options={'verbose_name': 'Fashion Art', 'verbose_name_plural': 'Fashion Arts'},
        ),
        migrations.AlterModelOptions(
            name='virtualinteractiveart',
            options={'verbose_name': 'Virtual & Interactive Art', 'verbose_name_plural': 'Virtual & Interactive Arts'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_helpful',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='source',
        ),
        migrations.AddField(
            model_name='artwork',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
