services:
  - type: web
    name: controlledmotives-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      mkdir -p media/artworks
      cp -r static_init_media/artworks/* media/artworks/ || echo "No media to copy"
      gunicorn controlledmotives.wsgi:application --bind 0.0.0.0:$PORT
    postDeployCommand: |
      python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "controlledmotives.settings"
      - key: ALLOWED_HOSTS
        value: "controlledmotives-backend.onrender.com,controlledmotives-frontend.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: controlledmotivesdb
          property: connectionString
      - key: STRIPE_SECRET_KEY
        value: "sk_test_dummy1234567890"

  - type: web
    name: controlledmotives-frontend
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: serve -s build
    runtime: nodejs16.x
    envVars:
      - key: REACT_APP_API_URL
        value: "https://controlledmotives-backend.onrender.com"
      - key: NODE_ENV
        value: "production"
