services:
  - type: web
    name: controlledmotives-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn controlledmotives.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "controlledmotives.settings"
      - key: ALLOWED_HOSTS
        value: "controlledmotives.onrender.com,controlledmotives-frontend.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: controlledmotives-db
          property: connectionString
    runtime: python3.9   # Explicitly set the runtime to Python 3.9 (or whatever version you need)

  - type: web
    name: controlledmotives-frontend
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://controlledmotives-backend.onrender.com"
      - key: NODE_ENV
        value: "production"
    runtime: nodejs16.x   # Use the desired Node.js runtime version
